### ISSUE TITLE
Potentionally rename uil namespace

### ISSUE THREAD

**Issue by tymees** [DH-IT-Portal-Development/django-shared-core#33]
As the ownership of this project might be moving soon, we might want to rename the `uil` package to something else. (`cdh`? `dh_it`?)

Ideally this will be part of the v2.1 release, as that release uses its own models for some functionality. (As renaming apps, and thus model namespaces, is very involved and annoying).

**Comment by tymees** [comment]
@miggol thoughts?

**Comment by miggol** [comment]
I like `cdh` because it's short and unintrusive, and also easy to type. It might come back to bite us if we want to use that app name elsewhere, or if the powers that be decide that we deserve a new name. But I'm willing to take those risks.

**Comment by tymees** [comment]
> if the powers that be decide that we deserve a new name
In which case we'd just tell them no-one except the devs will see the name ;)

Okay, I'll change the namespace to `cdh` at some point then. Probably after the next 2.1 alpha; That way you'll be able to use the alpha by just changing the version and not have to worry about changing imports just yet.
