### ISSUE TITLE
Show .invalid-feedback elements in forms

### ISSUE THREAD

**Issue by bbonf** [DH-IT-Portal-Development/django-shared-core#53]
When submitting an invalid form, `is-invalid` is correctly set on the fields containing errors, and the relevant `invalid-feedback` divs are created. However these have `display: none` set by default on bootstrap.
If I got it right, the feedback divs are supposed to be displayed using the selector `.is-invalid ~ .invalid-feedback`, but that doesn't apply to the cdh form templates because the feedback divs don't immediately follow the form fields.

Am I missing something to get this working?

**Comment by tymees** [comment]
Do you have an example for me?

I have it working just fine:
![image](https://user-images.githubusercontent.com/7061963/211850839-e7e6ed56-c0ab-497d-baa3-0bc5da5a9989.png)

**Comment by bbonf** [comment]
I can't seem to reproduce it. I'll reopen if I run into it again.

**Comment by tymees** [comment]
I've been able to reproduce it actually, using the BootstrapCheckboxInput, the BootstrapRadioSelect and the BootstrapCheckboxSelectMultiple widgets.

Those indeed don't follow a field. But they are 100% Bootstrap compliant, so I'm actually a bit puzzled why they don't work.

I'll look into it further

**Comment by tymees** [comment]
Figured out the problem, a fix should be ready before the end of next week

**Comment by tymees** [comment]
Fixed in 3.0.1
